@https = https://localhost:7033
@http = http://localhost:5133
@WebAPI_HostAddress = {{https}}

# Health - Liveness
GET {{WebAPI_HostAddress}}/health/live
Accept: application/json

###

# Health - Readiness (includes custom JSON writer)
GET {{WebAPI_HostAddress}}/health/ready
Accept: application/json

###

# Weather Forecast
GET {{WebAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

# OpenAPI document (if NSwag is enabled in Development)
GET {{WebAPI_HostAddress}}/swagger/v1/swagger.json
Accept: application/json

###

# Todos Items - Get all
GET {{WebAPI_HostAddress}}/todoItems?page=1&total=10&sortBy=id&descending=true
Accept: application/json

###

# Create Todos Item
POST {{WebAPI_HostAddress}}/todoItems
Content-Type: application/json

{
  "title": "Read a book"
}

###